name: "Hello-world-github-action-solution"
description: "Say hello to everyone."
inputs: 
  who-to-greet: 
    description: "Who to greet"
    required: true
    default: 'World'
outputs:
  - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "Keyvault-1-basic" # name of key vault in Azure portal
        secrets: 'mySecret'  # comma separated list of secret keys to fetch from key vault 
      id: myGetSecretAction # ID for secrets that you will reference

runs:
  using: 'node16'
  main: 'dist/index.js'
