name: "Hello-world-github-action-solution"
description: "Say hello to everyone."
inputs: 
  who-to-greet: 
    description: "Who to greet"
    required: true
    default: 'World'
outputs:
  time:
    description: 'time I greeted you'
    

runs:
  using: 'node16'
  main: 'dist/index.js'
