name: "Test Action-Solution"
description: "test repo for pooja."
inputs: 
  who-to-greet:
    description: "Who to greet"
    required: true
    default: 'World'
  ConnectedServiceName:
    description: "Input Service connection to authenticate to azure key vault for fetching gateway auth & signing cert."
    required: true
    default: ""

runs:
  using: 'node16'
  main: 'dist/index.js'